apiVersion: v1
kind: Pod
metadata:
  name: tensorboard
spec:
  containers:
  - name: tensorboard
    image: fewu/mask-rcnn-tensorflow:dev-master
    command: ["tensorboard"]
    args: ["--logdir=/fsx"]
    securityContext:
      privileged: true
    volumeMounts:
    - name:  fsx # efs or fsx
      mountPath: /fsx # /efs or /fsx
    ports:
    - containerPort: 6006
    # https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/
    #

  volumes:
  - name:  fsx # efs or fsx
    persistentVolumeClaim:
      claimName: tensorpack-fsx
